"""Stochastic 3D IFS volumes generated by the chaos game."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import numpy as np


MapInput = tuple[Any, Any, float] | dict[str, Any]


def _normalise_maps(maps: Sequence[MapInput]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if not maps:
        raise ValueError("maps must not be empty")

    matrices = []
    offsets = []
    probs = []
    for item in maps:
        if isinstance(item, dict):
            A = item.get("A")
            b = item.get("b")
            p = item.get("prob", item.get("probability", 1.0))
        else:
            A, b, p = item
        matrices.append(np.asarray(A, dtype=np.float32).reshape(3, 3))
        offsets.append(np.asarray(b, dtype=np.float32).reshape(3))
        probs.append(float(p))

    prob_arr = np.asarray(probs, dtype=np.float64)
    total = float(prob_arr.sum())
    if total <= 0:
        raise ValueError("map probabilities must sum to a positive value")
    prob_arr /= total
    return np.stack(matrices), np.stack(offsets), prob_arr


def ifs3d_volume(
    maps: Sequence[MapInput],
    N: int = 192,
    n_points: int = 2_000_000,
    warmup: int = 20,
    seed: int | None = 12345,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(occupancy, density_field)`` for a 3D IFS chaos game."""
    N = int(N)
    n_points = int(n_points)
    warmup = int(warmup)
    if N < 8:
        raise ValueError("N must be at least 8")
    if n_points < 1:
        raise ValueError("n_points must be positive")
    if warmup < 0:
        raise ValueError("warmup must be non-negative")

    A, b, probs = _normalise_maps(maps)
    rng = np.random.default_rng(seed)
    choices = rng.choice(len(probs), size=n_points + warmup, p=probs)

    p = np.zeros(3, dtype=np.float32)
    points = np.empty((n_points, 3), dtype=np.float32)
    out_i = 0
    for step, map_i in enumerate(choices):
        p = A[map_i] @ p + b[map_i]
        if step >= warmup:
            points[out_i] = p
            out_i += 1

    mn = points.min(axis=0)
    mx = points.max(axis=0)
    span = np.where((mx - mn) > 1e-9, mx - mn, 1.0)
    norm = (points - mn) / span
    idx = np.clip((norm * (N - 1)).astype(np.int32), 0, N - 1)

    density = np.zeros((N, N, N), dtype=np.float32)
    np.add.at(density, (idx[:, 0], idx[:, 1], idx[:, 2]), 1.0)

    occupancy = density > 0
    color_field = np.log1p(density).astype(np.float32)

    x = np.linspace(0.0, 1.0, N, dtype=np.float32)[:, None, None]
    y = np.linspace(0.0, 1.0, N, dtype=np.float32)[None, :, None]
    z = np.linspace(0.0, 1.0, N, dtype=np.float32)[None, None, :]
    color_field += 0.25 * (0.45 * x + 0.35 * y + 0.20 * z)
    return occupancy, color_field


def sierpinski_tetrahedron_maps() -> list[tuple[np.ndarray, np.ndarray, float]]:
    """Return the canonical 4-map Sierpinski tetrahedron IFS."""
    vertices = np.asarray(
        [
            [1.0, 1.0, 1.0],
            [1.0, -1.0, -1.0],
            [-1.0, 1.0, -1.0],
            [-1.0, -1.0, 1.0],
        ],
        dtype=np.float32,
    )
    scale = np.float32(0.5)
    A = np.eye(3, dtype=np.float32) * scale
    return [(A.copy(), scale * v, 0.25) for v in vertices]


def sierpinski_tetrahedron_volume(
    N: int = 192,
    n_points: int = 2_000_000,
    warmup: int = 20,
    seed: int | None = 12345,
) -> tuple[np.ndarray, np.ndarray]:
    """Return a volume for the Sierpinski tetrahedron preset."""
    return ifs3d_volume(
        sierpinski_tetrahedron_maps(),
        N=N,
        n_points=n_points,
        warmup=warmup,
        seed=seed,
    )
